PROMPT
PROMPT ==> FUNÇÃO: INFORMAÇÕES DA INSTANCE E DO BANCO DE DADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	INSTANCE_NAME,
       	GLOBAL_NAME,
       	USER,
       	LOGINS,
       	HOST_NAME
FROM   
	V$INSTANCE, GLOBAL_NAME
/
