DROP TABLE DML_VALUES;

CREATE TABLE DML_VALUES (SELECT_COMMAND VARCHAR2(4000));

DROP TABLE INSERT_VALUES;

CREATE TABLE INSERT_VALUES (INSERT_COMMAND VARCHAR2(4000));

CREATE OR REPLACE PROCEDURE PR_GERA_INSERT (P_OWNER VARCHAR2, P_TABLE_NAME VARCHAR2) AS

	V_COLUMNS	VARCHAR2(4000);
	V_FOR_COLUMNS	VARCHAR2(4000);
	V_FINAL		VARCHAR2(4000);
	V_OWNER		DBA_TAB_COLUMNS.OWNER%TYPE;
	V_TABLE_NAME	DBA_TAB_COLUMNS.TABLE_NAME%TYPE;
	V_QTD_LOB	PLS_INTEGER;
	V_EXIST		PLS_INTEGER;

	CURSOR GET_COLUMNS IS
	SELECT
		COLUMN_NAME||',' AS COLUMN_NAME
	FROM
		DBA_TAB_COLUMNS
	WHERE
		OWNER		= UPPER(V_OWNER) 	AND
		TABLE_NAME 	= UPPER(V_TABLE_NAME);

	CURSOR GET_FOR_COLUMNS IS
	SELECT
		DECODE(DATA_TYPE,'NUMBER','',''''''||''''''||'||')||COLUMN_NAME||DECODE(DATA_TYPE,'NUMBER','','||'||''''''||'''''')||'||'||''','''||'||' AS COLUMN_NAME
	FROM
		DBA_TAB_COLUMNS
	WHERE
		OWNER		= UPPER(V_OWNER) 	AND
		TABLE_NAME 	= UPPER(V_TABLE_NAME);

BEGIN

	EXECUTE IMMEDIATE 'TRUNCATE TABLE DML_VALUES';
	EXECUTE IMMEDIATE 'TRUNCATE TABLE INSERT_VALUES';

	V_COLUMNS 	:= NULL;
	V_FOR_COLUMNS 	:= NULL;
	V_FINAL		:= NULL;

	V_OWNER		:= P_OWNER;
	V_TABLE_NAME	:= P_TABLE_NAME;

	V_QTD_LOB	:= 0;
	V_EXIST		:= 0;

	SELECT
		COUNT(*)
	INTO
		V_QTD_LOB
	FROM
		DBA_TAB_COLUMNS
	WHERE
		OWNER		= UPPER(V_OWNER) 	AND
		TABLE_NAME 	= UPPER(V_TABLE_NAME)	AND
		DATA_TYPE 	LIKE '%LOB%';

	SELECT
		COUNT(*)
	INTO
		V_EXIST
	FROM
		DBA_TABLES
	WHERE
		OWNER		= UPPER(V_OWNER) 	AND
		TABLE_NAME 	= UPPER(V_TABLE_NAME)	;

	IF V_EXIST > 0 THEN

		IF V_QTD_LOB > 0 THEN
			DBMS_OUTPUT.PUT_LINE('A TABELA CONTEM CAMPOS LOB, IMPOSSIVEL CONTINUAR');
		ELSE

			FOR REC_COLUMNS IN GET_COLUMNS LOOP
				V_COLUMNS := V_COLUMNS || REC_COLUMNS.COLUMN_NAME;
			END LOOP;

			FOR REC_FOR_COLUMNS IN GET_FOR_COLUMNS LOOP
				V_FOR_COLUMNS := V_FOR_COLUMNS || REC_FOR_COLUMNS.COLUMN_NAME;
			END LOOP;

			V_FINAL	:= 'SELECT '||''''||'INSERT INTO '||UPPER(V_OWNER)||'.'||UPPER(V_TABLE_NAME)||' ('||SUBSTR(V_COLUMNS,1,LENGTH(V_COLUMNS)-1)||') VALUES ('||''''||'||'||SUBSTR(V_FOR_COLUMNS,1,LENGTH(V_FOR_COLUMNS)-4)||');'||''''||' FROM '||V_OWNER||'.'||V_TABLE_NAME||';';

			INSERT INTO DML_VALUES (SELECT_COMMAND) VALUES (V_FINAL);

			EXECUTE IMMEDIATE 'INSERT INTO INSERT_VALUES (INSERT_COMMAND) '||SUBSTR(V_FINAL,1,LENGTH(V_FINAL)-1);
	
			COMMIT;

		END IF;
	ELSE
		DBMS_OUTPUT.PUT_LINE('A TABELA NAO EXISTE');	
	END IF;
END;
/