SELECT
 TRUNC(DATA) "DATA",
 USERNAME,
 OSUSER,
 MACHINE,
 MAX(LAST_CALL_ET) AS "MAIOR TEMPO DE INATIVIDADE",
 CASE WHEN (MAX(LAST_CALL_ET) <= 3600) THEN
 'ATÉ 1 HORA'
 WHEN (MAX(LAST_CALL_ET) > 3600) AND (MAX(LAST_CALL_ET) <= 7200)  THEN
 '1 À 2 HORAS'
 WHEN (MAX(LAST_CALL_ET) > 7200) AND (MAX(LAST_CALL_ET) <= 10800)  THEN
 '2 À 3 HORAS'
 ELSE
 ' 3 HORAS OU MAIS'
 END "TEMPO DE INATIVIDADE"
FROM SESSIONS
WHERE TRUNC(DATA) BETWEEN TO_CHAR('01/04/04') AND TO_CHAR('30/04/04')
AND STATUS = 'INACTIVE'
AND   USERNAME NOT IN('FNDASAPP','CORONA','SYSTEM','SYS','LINKUSER','IFSAPPBR')
AND   LAST_CALL_ET > 1800
GROUP BY 
	TRUNC(DATA),
	USERNAME,
	OSUSER,
	MACHINE
ORDER BY
	5 DESC, 1 ASC
/
