PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS ÍNDICES E SUAS COLUNAS PARA TABELA
PROMPT
--BREAK ON INDEX_NAME
SELECT
	INDEX_NAME,
	COLUMN_NAME,
	COLUMN_POSITION,
	TABLE_OWNER,
	TABLE_NAME,
	INDEX_OWNER
FROM
	DBA_IND_COLUMNS
WHERE
	TABLE_NAME = UPPER('&TABLE')

ORDER BY
	INDEX_NAME, COLUMN_POSITION ASC
/
