PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE OS ÍNDICES MONITORADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT
	*
FROM
	V$OBJECT_USAGE
/