-- Diagnostico para library cache pin e library cache load lock

SET LINESIZE 90
COLUMN USRLOCKED FORMAT A12 HEAD "Usr|Lock"
COLUMN USRBLOCK FORMAT A12 HEAD "Usr|Block"
COLUMN OBJECT FORMAT A20 WORD_WRAP
COLUMN SIDL FORMAT 9999 HEAD "Sid|lock"
COLUMN SIDB FORMAT 9999 HEAD "Sid|Block"
COLUMN REQLMOD FORMAT A4 HEAD "Req:|Lmode"
BREAK ON SIDL
SELECT STRAVADA.SID SIDL,STRAVADA.USERNAME USRLOCKED,
STRAVANTE.SID SIDB,STRAVANTE.USERNAME USRBLOCK,TO_CHAR(STRAVANTE.LOGON_TIME,'DD/MM/YY HH24:MI')LOGTIMEBLOCK,
O.KGLNAOWN || '.' || O.KGLNAOBJ OBJECT,
DECODE(PIN1.KGLPNREQ,2,'S',3,'X',0,'N','U') ||':'|| DECODE(PIN2.KGLPNMOD,2,'S',3,'X',0,'N','U') REQLMOD
FROM V$SESSION STRAVADA, V$SESSION STRAVANTE,
X$KGLOB O, X$KGLPN PIN2, X$KGLPN PIN1
WHERE PIN1.KGLPNREQ > 0
AND PIN2.KGLPNHDL = PIN1.KGLPNHDL
AND PIN2.KGLPNREQ = 0
AND O.KGLHDADR = PIN1.KGLPNHDL
AND STRAVANTE.SADDR = PIN2.KGLPNUSE
AND STRAVADA.SADDR = PIN1.KGLPNUSE
ORDER BY SIDL
/