col object format a30
col username format a30
col osuser   format a30
SELECT 
  l1.sid sid_locking,
  s1.serial# serial#_locking,
  s1.username user_locking,
  s1.osuser osuser_locking,
  s1.sql_hash_value hash_value_locking,
  'IS BLOCKING',
  l2.sid sid_blocked,
  s2.serial# serial#_blocked,
  s2.username user_blocked,
  s2.osuser osuser_blocked,
  s2.sql_hash_value hash_value_blocked,
  decode(l1.type, 
  'BL','Buffer hash table', 
  'CF','Control File Transaction', 
  'CI','Cross Instance Call', 
  'CS','Control File Schema', 
  'CU','Bind Enqueue', 
  'DF','Data File', 
  'DL','Direct-loader index-creation', 
  'DM','Mount/startup db primary/secondary instance', 
  'DR','Distributed Recovery Process', 
  'DX','Distributed Transaction Entry', 
  'FI','SGA Open-File Information', 
  'FS','File Set', 
  'IN','Instance Number', 
  'IR','Instance Recovery Serialization', 
  'IS','Instance State', 
  'IV','Library Cache InValidation', 
  'JQ','Job Queue', 
  'KK','Redo Log "Kick"', 
  'LS','Log Start/Log Switch', 
  'MB','Master Buffer hash table', 
  'MM','Mount Definition', 
  'MR','Media Recovery', 
  'PF','Password File', 
  'PI','Parallel Slaves', 
  'PR','Process Startup', 
  'PS','Parallel Slaves Synchronization', 
  'RE','USE_ROW_ENQUEUE Enforcement', 
  'RT','Redo Thread', 
  'RW','Row Wait', 
  'SC','System Commit Number', 
  'SH','System Commit Number HWM', 
  'SM','SMON', 
  'SQ','Sequence Number', 
  'SR','Synchronized Replication', 
  'SS','Sort Segment', 
  'ST','Space Transaction', 
  'SV','Sequence Number Value', 
  'TA','Transaction Recovery', 
  'TD','DDL enqueue', 
  'TE','Extend-segment enqueue', 
  'TM','DML enqueue', 
  'TS','Temporary Segment', 
  'TT','Temporary Table', 
  'TX','Transaction', 
  'UL','User-defined Lock', 
  'UN','User Name', 
  'US','Undo Segment Serialization', 
  'WL','Being-written redo log instance', 
  'WS','Write-atomic-log-switch global enqueue', 
  'XA','Instance Attribute', 
  'XI','Instance Registration', 
decode(substr(l1.TYPE,1,1), 
  'L','Library Cache ('||substr(l1.TYPE,2,1)||')', 
  'N','Library Cache Pin ('||substr(l1.TYPE,2,1)||')', 
  'Q','Row Cache ('||substr(l1.TYPE,2,1)||')', 
  '????')) locking_type,
  decode(l2.type, 
  'BL','Buffer hash table', 
  'CF','Control File Transaction', 
  'CI','Cross Instance Call', 
  'CS','Control File Schema', 
  'CU','Bind Enqueue', 
  'DF','Data File', 
  'DL','Direct-loader index-creation', 
  'DM','Mount/startup db primary/secondary instance', 
  'DR','Distributed Recovery Process', 
  'DX','Distributed Transaction Entry', 
  'FI','SGA Open-File Information', 
  'FS','File Set', 
  'IN','Instance Number', 
  'IR','Instance Recovery Serialization', 
  'IS','Instance State', 
  'IV','Library Cache InValidation', 
  'JQ','Job Queue', 
  'KK','Redo Log "Kick"', 
  'LS','Log Start/Log Switch', 
  'MB','Master Buffer hash table', 
  'MM','Mount Definition', 
  'MR','Media Recovery', 
  'PF','Password File', 
  'PI','Parallel Slaves', 
  'PR','Process Startup', 
  'PS','Parallel Slaves Synchronization', 
  'RE','USE_ROW_ENQUEUE Enforcement', 
  'RT','Redo Thread', 
  'RW','Row Wait', 
  'SC','System Commit Number', 
  'SH','System Commit Number HWM', 
  'SM','SMON', 
  'SQ','Sequence Number', 
  'SR','Synchronized Replication', 
  'SS','Sort Segment', 
  'ST','Space Transaction', 
  'SV','Sequence Number Value', 
  'TA','Transaction Recovery', 
  'TD','DDL enqueue', 
  'TE','Extend-segment enqueue', 
  'TM','DML enqueue', 
  'TS','Temporary Segment', 
  'TT','Temporary Table', 
  'TX','Transaction', 
  'UL','User-defined Lock', 
  'UN','User Name', 
  'US','Undo Segment Serialization', 
  'WL','Being-written redo log instance', 
  'WS','Write-atomic-log-switch global enqueue', 
  'XA','Instance Attribute', 
  'XI','Instance Registration', 
decode(substr(l2.TYPE,1,1), 
  'L','Library Cache ('||substr(l2.TYPE,2,1)||')', 
  'N','Library Cache Pin ('||substr(l2.TYPE,2,1)||')', 
  'Q','Row Cache ('||substr(l2.TYPE,2,1)||')', 
  '????')) blocked_type
FROM 
  v$lock l1,
  v$lock l2,
  v$session s1,
  v$session s2
WHERE 
    l1.block =1
AND l2.request > 0
AND l1.id1     =l2.id1
AND l1.id2     =l2.id2
AND s1.sid      = l1.sid
AND s2.sid      = l2.sid
/