PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE AS LINHAS MIGRADAS/ENCADEADAS DAS TABELAS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
COL "OWNER TABLE" FORMAT A12
SELECT
	A.OWNER      			AS "OWNER TABLE",
	A.TABLE_NAME 			AS "TABLE NAME", 
	A.CHAIN_CNT  			AS "MIGRATED/CHAINED",
	A.NUM_ROWS   			AS "NUMBER ROWS",
	ROUND(A.CHAIN_CNT*100/(A.NUM_ROWS),2) AS "PERCENTAGE OF MIGRATED/CHAINED",
	ROUND(B.BYTES/1024/1024,2) 	AS "SEGMENT BYTES"
FROM
	DBA_TABLES 	A,
	DBA_SEGMENTS 	B
WHERE
	A.TABLE_NAME 		= B.SEGMENT_NAME
	AND A.CHAIN_CNT 	> 0
	AND A.NUM_ROWS 		> 0
	AND A.OWNER NOT IN 	('SYS','SYSTEM')
ORDER BY
	5 DESC
/
