SET SERVEROUTPUT ON SIZE 1000000
UNDEFINE TABLESPACE_ORIGEM_D_
UNDEFINE TABLESPACE_ORIGEM_I_
UNDEFINE TABLESPACE_DESTINO_D_
UNDEFINE TABLESPACE_DESTINO_I_
ACCEPT TABLESPACE_ORIGEM_D_ 	PROMPT 'TABLESPACE DE DADOS   - ORIGEM ......: '
ACCEPT TABLESPACE_ORIGEM_I_ 	PROMPT 'TABLESPACE DE INDICES - ORIGEM ......: '
ACCEPT TABLESPACE_DESTINO_D_ 	PROMPT 'TABLESPACE DE DADOS   - DESTINO .....: '
ACCEPT TABLESPACE_DESTINO_I_ 	PROMPT 'TABLESPACE DE INDICES - DESTINO .....: '
SPOOL C:\REORG_TABLES_INDEXES.SQL
DECLARE

	TABLE_NAME_  DBA_TABLES.TABLE_NAME%TYPE;
	TABLE_OWNER_ DBA_INDEXES.TABLE_OWNER%TYPE;
	INDEX_OWNER_ DBA_INDEXES.OWNER%TYPE;
	INDEX_NAME_  DBA_INDEXES.INDEX_NAME%TYPE;
	BYTES_	     DBA_SEGMENTS.BYTES%TYPE;
	QTDE_	     NUMBER(2);

	CURSOR GET_TABLE_ IS
	SELECT 
		OWNER, 
		SEGMENT_NAME,
		BYTES
	FROM 
		DBA_SEGMENTS
	WHERE 
		TABLESPACE_NAME 	= '&&TABLESPACE_ORIGEM_D_'
   		-- AND BYTES 		< 800*1024*1024
		AND SEGMENT_TYPE 	= 'TABLE'
	ORDER BY 
		BYTES DESC;

	CURSOR GET_INDEX_TABLE_ IS
	SELECT
		OWNER,
		INDEX_NAME
	FROM
		DBA_INDEXES
	WHERE
		TABLE_NAME 		= TABLE_NAME_
		AND TABLE_OWNER 	= TABLE_OWNER_;
BEGIN
	OPEN GET_TABLE_;
	LOOP
		EXIT WHEN GET_TABLE_%NOTFOUND;
		FETCH GET_TABLE_ INTO TABLE_OWNER_,TABLE_NAME_, BYTES_;
		
		DBMS_OUTPUT.PUT_LINE('ALTER TABLE '||'"'||TABLE_OWNER_||'"'||'.'||'"'||TABLE_NAME_||'"'||' MOVE TABLESPACE '
			||'&&TABLESPACE_DESTINO_D_'||';');

		-- DBMS_OUTPUT.PUT_LINE('ALTER TABLE '||'"'||TABLE_OWNER_||'"'||'.'||'"'||TABLE_NAME_||'"'||' MOVE TABLESPACE '
		--	||'&&TABLESPACE_DESTINO_D_'||' STORAGE (INITIAL '||TRUNC((BYTES_/1024)*1.2)||'K NEXT '||TRUNC((BYTES_/1024)/5)||'K PCTINCREASE 0);');
		
		FOR REC1 IN GET_INDEX_TABLE_
		LOOP
			SELECT 
				COUNT(*)  
			INTO
				QTDE_
			FROM 
				DBA_IND_COLUMNS 
			WHERE 
				INDEX_NAME = REC1.INDEX_NAME AND INDEX_OWNER = REC1.OWNER;
			
			IF QTDE_ > 1 THEN
				DBMS_OUTPUT.PUT_LINE('ALTER INDEX '||'"'||REC1.OWNER||'"'||'.'||'"'||REC1.INDEX_NAME||'"'||' REBUILD TABLESPACE '
				||'&&TABLESPACE_DESTINO_I_'||' ONLINE COMPUTE STATISTICS COMPRESS;');
			ELSE
				DBMS_OUTPUT.PUT_LINE('ALTER INDEX '||'"'||REC1.OWNER||'"'||'.'||'"'||REC1.INDEX_NAME||'"'||' REBUILD TABLESPACE '
				||'&&TABLESPACE_DESTINO_I_'||' ONLINE COMPUTE STATISTICS;');
			END IF;
		END LOOP;
	END LOOP;
	CLOSE GET_TABLE_;

END;
/
SPOOL OFF;
UNDEFINE TABLESPACE_ORIGEM_D_
UNDEFINE TABLESPACE_DESTNO_I_
UNDEFINE TABLESPACE_DESTINO_D_
UNDEFINE TABLESPACE_DESTINO_I_