PROMPT
PROMPT ==> FUNÇÃO: EXIBE O TABLESPACE QUE UM DETERMINADO SEGMENTO ESTÁ ALOCADO
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	OWNER,
	SEGMENT_NAME,
	PARTITION_NAME,
	TABLESPACE_NAME,
	SEGMENT_TYPE,
	BYTES/1024/1024
FROM 
	DBA_SEGMENTS
WHERE  
	SEGMENT_NAME = UPPER('&SEGMENT')
ORDER BY
	PARTITION_NAME
/
