PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS 10 COMANDOS SQL QUE MAIS EXIGEM RECURSOS DA INSTANCE
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
COL ADDRESS  FORMAT A20
COL SQL_TEXT FORMAT A100
SELECT 
	*
FROM
	(SELECT ADDRESS,
		SQL_TEXT,
	 	RANK() OVER
		(ORDER BY BUFFER_GETS DESC) AS RANK_BUFGETS,
		TO_CHAR(100 * RATIO_TO_REPORT(BUFFER_GETS) OVER(),'999.99') PCT_BUFGETS,
		EXECUTIONS
	 FROM
		V$SQL)
WHERE
	RANK_BUFGETS < 11
/
