PROMPT
PROMPT ==> FUNÇÃO: EXIBE O TEXTO DE UMA VIEW DO BANCO DE DADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SET LONG 4000
COL TEXT FORMAT A4000
SELECT 
	TEXT
FROM
	DBA_VIEWS
WHERE
	VIEW_NAME = UPPER('&VIEW')
/