PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS USUÁRIOS ATIVOS NA ESCALA DE SQL MAL CONSTRUÍDO
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	SQL.BUFFER_GETS,
	SQL.DISK_READS,
	SQL.EXECUTIONS,
	S.OSUSER, 
	S.USERNAME, 
	S.SID, 
	S.SERIAL#, 
	S.STATUS, 
	S.SERVER, 
	S.MACHINE, 
	S.PROGRAM
FROM   
	V$SESSION S,
	V$SQL     SQL
WHERE  
	USERNAME 	!= 'UNKNOW'	AND
	TYPE     		!= 'BACKGROUND'	AND    
	STATUS   	= 'ACTIVE'	AND
	SQL.HASH_VALUE	= S.SQL_HASH_VALUE
ORDER BY
	SQL.EXECUTIONS  ASC,
	SQL.BUFFER_GETS DESC,
	SQL.DISK_READS  DESC,
	S.USERNAME
/
