PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS USUÁRIOS QUE ESTÃO EM LOCK POR OUTRA SESSÃO
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT
	/*+ORDERED*/
	B.USERNAME,
	B.SERIAL#,
	D.ID1,
	A.SQL_TEXT
FROM
	V$LOCK 		D,
	V$SESSION 	B,
	V$SQLTEXT 	A
WHERE
	B.LOCKWAIT 		= D.KADDR
	AND A.ADDRESS 		= B.SQL_ADDRESS
	AND A.HASH_VALUE 	= B.SQL_HASH_VALUE
/