PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE OS USUÁRIOS CONECTADOS NA BASE DE DADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT
   S.USERNAME,
   S.OSUSER,
   S.SID,
   S.SERIAL#,
   P.SPID,
   S.STATUS,
   S.SERVER,
   S.MACHINE,
   S.MODULE,
   S.PROGRAM,
   TO_CHAR(S.LOGON_TIME,'DD/MM/YYYY HH24:MI:SS') LOGON,
   S.LAST_CALL_ET
FROM
   V$SESSION S,
   V$PROCESS P
WHERE
   P.ADDR          = S.PADDR
   AND S.STATUS    NOT IN ('KILLED')
   AND S.USERNAME != 'UNKNOW'
ORDER  BY
   S.USERNAME, S.OSUSER
/
