SET SERVEROUTPUT ON SIZE UNLIMITED;
SET LINES 32767;
SET PAGES 0;
SET TRIMSPOOL ON;
SET HEADING OFF;
SET FEEDBACK OFF;
SET VERIFY OFF;
SET TIMING OFF;
SET COLSEP ";";

SET AUTOTRACE OFF STATISTICS

-- Ativa trace de estatísticas
SET AUTOTRACE TRACE EXPLAIN STATISTICS

-- Ativa log de tempo
SET TIMING ON
