PROMPT
PROMPT ==> FUNÇÃO: SCRIPT QUE RETORNA QUAIS OS PROCESSOS EM BACKGROUND ATIVOS NA BASE
PROMPT
SELECT
	 A.SID,
         A.SERIAL#,
         B.DESCRIPTION,
         A.STATUS
FROM
	 V$BGPROCESS B,
         V$SESSION   A
WHERE
         A.PADDR = B.PADDR
ORDER BY 3
/
