LOAD DATA
INFILE '##FILE##'
APPEND INTO TABLE CAPACITY.TOUT_GC
FIELDS TERMINATED BY ';'
(
SISTEMA_ID,
CONSOLE_ID,
HOSTNAME,
INSTANCIA,
DATA     "to_date(:DATA,'yyyy-mm-dd hh24:mi:ss____')",
EXEC_TYPE,
FILE_TIME FILLER,
GC_ANTES,
GC_DEPOIS,
GC_TAMANHO,
TEMPO)
