

SET LINES 155
COL EXECS FOR 999,999,999
COL AVG_ETIME FOR 999,999.999
COL AVG_LIO FOR 999,999,999.9
COL BEGIN_INTERVAL_TIME FOR A30
COL NODE FOR 99999
BREAK ON PLAN_HASH_VALUE ON STARTUP_TIME SKIP 1
SELECT SS.SNAP_ID, SS.INSTANCE_NUMBER NODE, BEGIN_INTERVAL_TIME, SQL_ID, PLAN_HASH_VALUE,
NVL(EXECUTIONS_DELTA,0) EXECS,
(ELAPSED_TIME_DELTA/DECODE(NVL(EXECUTIONS_DELTA,0),0,1,EXECUTIONS_DELTA))/1000000 AVG_ETIME,
(BUFFER_GETS_DELTA/DECODE(NVL(BUFFER_GETS_DELTA,0),0,1,EXECUTIONS_DELTA)) AVG_LIO
FROM DBA_HIST_SQLSTAT S, DBA_HIST_SNAPSHOT SS
WHERE SQL_ID = '&sql_id'
AND SS.SNAP_ID = S.SNAP_ID
AND SS.INSTANCE_NUMBER = S.INSTANCE_NUMBER
AND EXECUTIONS_DELTA > 0
ORDER BY 1, 2, 3
/
