PROMPT
PROMPT ==> FUNÇÃO: MOSTRA O TAMANHO E DESCRIÇÃO DOS DATAFILES
PROMPT
SELECT
	FILE_NAME       ARQUIVO   ,
	FILE_ID                   ,
	TABLESPACE_NAME TABLESPACE,
	BYTES/1024/1024 MB        ,
	BLOCKS,
	AUTOEXTENSIBLE,
	MAXBYTES/1024/1024 MAX_MEGABYTES
FROM
	DBA_DATA_FILES
ORDER BY
	MB DESC
/