PROMPT
PROMPT ==> FUNÇÃO: GERA COMANDOS DE COMPILAÇÃO E GRAVA EM ARQUIVO DE SPOOL
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SET TIMING OFF
SET PAGES 0
SET LINES 100
SET FEED OFF
spool recompile.sql
select 
	DISTINCT 'ALTER '||
	DECODE(OBJECT_TYPE,'PACKAGE BODY','PACKAGE',OBJECT_TYPE)||
	' '||'"'||OWNER||'"'||'.'||'"'||OBJECT_NAME||'"'||' COMPILE '||
	DECODE(OBJECT_TYPE,'PACKAGE BODY','BODY')||';'
FROM 
	DBA_OBJECTS
WHERE 
	STATUS = 'INVALID'
	AND   	OBJECT_TYPE != 'UNDEFINED'
/
SPOOL OFF
PROMPT
PROMPT ============================================
PROMPT PARA RECOMPILAR, EXECUTE @RECOMPILE.SQL -->>
PROMPT ============================================
SET FEED ON
@LOGIN