PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS JOBS QUE ESTÃO EM EXECUÇÃO NO MOMENTO
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	/*+ rule*/
	*
FROM 
	DBA_JOBS_RUNNING
/
