SELECT 
	KGLNAOBJ OBJ,
	S.USERNAME,
	S.SID,KGLLKREQ REQUEST,
	KGLLKMOD LOCK_MODE
FROM 
	X$KGLLK LK, 
	V$SESSION S 
WHERE 
	LK.KGLLKHDL IN (SELECT P1RAW FROM V$SESSION_WAIT WHERE EVENT = 'library cache lock')
	AND S.SADDR = LK.KGLLKSES;