PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE OS OBJETOS CRIADOS NO BANCO DE DADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	OWNER, 
	OBJECT_TYPE, 
	COUNT(*) QUANTITY
FROM 
	DBA_OBJECTS
WHERE 
	OWNER NOT IN ('SYS','SYSTEM','OUTLN','WMSYS','PUBLIC')
GROUP BY 
	OWNER, OBJECT_TYPE
/