PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS OWNERS DO BANCO DE DADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	DISTINCT(OWNER) AS "OWNERS"
FROM   
	DBA_OBJECTS
/
