SELECT * FROM (
SELECT Trunc(MINFRA_DATA,'MM') DATA,
    HOSTNAME,
    MINFRA_ID,
    PERCENTILE_DISC(0.9) WITHIN GROUP ( ORDER BY MINFRA_VALUE ASC) MINFRA_VALUE
  FROM CAPACITY.TMINFRA_SERVIDOR
  WHERE HOSTNAME IN (SELECT HOSTNAME FROM vsistema_servidores_v2 WHERE SISTEMA_ID=53 AND STATUS_ID='A')
  AND MINFRA_DATA >= TRUNC(ADD_MONTHS(SYSDATE,   -1),'MM')
  AND MINFRA_DATA <= LAST_DAY(ADD_MONTHS(SYSDATE,-1))
  AND MINFRA_ID                                 IN (101, 102, 107,103)
  GROUP BY Trunc(MINFRA_DATA,'MM'),
    HOSTNAME,
    MINFRA_ID
)
pivot (sum(minfra_value) FOR minfra_id IN (101 AS CPU, 107 AS mem, 102 AS disk , 103 AS load ));