PROMPT
PROMPT ==> FUNÇÃO: EXIBE A QUANTIDADE DE TABELA QUE A TABELA POSSUÍA NA ÚLTIMA ANÁLISE
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	OWNER, 
	TABLE_NAME, 
	BLOCKS, 
	NUM_ROWS
FROM   
	DBA_TABLES
WHERE  
	TABLE_NAME = UPPER('&TABLE')
/
