PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS USUÁRIOS ATIVOS NA BASE
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	USERNAME, 
	OSUSER, 
	SID, 
	SERIAL#, 
	STATUS, 
	SERVER, 
	MACHINE, 
	MODULE,
	PROGRAM, 
	TO_CHAR(LOGON_TIME,'DD/MM/YYYY HH24:MI:SS') LOGON,
	LAST_CALL_ET
FROM   
	GV$SESSION
WHERE  
	STATUS   	= 'ACTIVE'
	AND USERNAME != 'UNKNOW'
ORDER  BY 
	USERNAME, OSUSER
/