PROMPT
PROMPT ==> FUNÇÃO: EXIBE OS SEGMENTOS COM CHANCE DE ESTOURAR O TAMANHO DO TABLESPACE
PROMPT ==> NA PRÓXIMA ALOCAÇÃO DE EXTENT
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	S.SEGMENT_NAME,
	S.SEGMENT_TYPE,
	S.EXTENTS,
	S.MAX_EXTENTS,
	S.TABLESPACE_NAME
FROM   
	DBA_SEGMENTS S
WHERE  
	S.NEXT_EXTENT > 	(SELECT
					MAX(F.BYTES) 
				FROM 
					DBA_FREE_SPACE F
				WHERE 
					F.TABLESPACE_NAME = S.TABLESPACE_NAME)
/
