PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE OS PRIVILÉGIOS DE UM USUÁRIO/ROLE SOBRE TABELAS, PROCEDURES, ETC.
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
ACCEPT ROLEUSER PROMPT "DIGITE O NOME DO USUÁRIO OU ROLE...: "
SELECT
	*
FROM
	DBA_TAB_PRIVS
WHERE
	GRANTEE = UPPER('&ROLEUSER')
/
UNDEFINE ROLEUSER