PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE OS SEGMENTOS TEMPORÁRIOS QUE ESTÃO SENDO UTILIZADOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT 
	USERNAME, 
	USER, 
	SESSION_ADDR, 
	SESSION_NUM, 
	TABLESPACE, 
	CONTENTS, 
	SEGTYPE, 
	SEGFILE#, 
	EXTENTS, 
	BLOCKS
FROM 
	V$TEMPSEG_USAGE
/