PROMPT
PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES DE CONSUMO DE RECURSOS DOS USUÁRIOS ATIVOS
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
SELECT
	A.USERNAME,
	A.OSUSER,
	B.BLOCK_GETS,
	B.CONSISTENT_GETS,
	B.PHYSICAL_READS,
	B.BLOCK_CHANGES,
	B.CONSISTENT_GETS,
	A.SID,
	A.SERIAL#
FROM
	V$SESSION A,
	V$SESS_IO B
WHERE
	A.SID = B.SID
	AND A.STATUS = 'ACTIVE'
	AND A.USERNAME != 'UNKNOW'
ORDER BY
	3 DESC, 4 DESC, 5 DESC, 6 DESC, 7 DESC
/