PROMPT ==> FUNÇÃO: EXIBE INFORMAÇÕES SOBRE AS ROLES QUE DETERMINADO USUÁRIO POSSUI PERMISSÃO
PROMPT ==> DESENVOLVIDO POR CLEBER R. MARQUES
PROMPT ==> MSN: cleber_rmarques@hotmail.com
PROMPT
ACCEPT USER PROMPT "DIGITE O NOME DO USUÁRIO...: "
SELECT
	*
FROM
	DBA_ROLE_PRIVS
WHERE
	GRANTEE = UPPER('&USER')
/
UNDEFINE USER